scrape_configs:
  - job_name: "catsdogs-api"
    metrics_path: /metrics
    static_configs:
      - targets: ["catsdogs-api:8000"]

  - job_name: "mlflow"
    metrics_path: /metrics
    static_configs:
      - targets: ["mlflow:5000"]