apiVersion: v1
kind: ConfigMap
metadata:
  name: catsdogs-api-config
  namespace: catsdogs-mlops
data:
  APP_ENV: "production"

  MODEL_LOAD_RETRY: "true"
  MODEL_LOAD_RETRY_SECONDS: "20"

  # Registry-based serving
  MLFLOW_TRACKING_URI: "http://mlflow:5000"
  MLFLOW_MODEL_NAME: "cats-dogs"
  MLFLOW_MODEL_STAGE: "Production"

  # MinIO/S3 artifact access (required for your setup)
  MLFLOW_S3_ENDPOINT_URL: "http://minio:9000"
  AWS_DEFAULT_REGION: "us-east-1"
