apiVersion: v1
kind: Secret
metadata:
  name: catsdogs-api-secret
  namespace: catsdogs-mlops
type: Opaque
stringData:
  ADMIN_API_KEY: "supersecret"
  AWS_ACCESS_KEY_ID: "minioadmin"
  AWS_SECRET_ACCESS_KEY: "minioadmin123"
