apiVersion: v1
kind: Service
metadata:
  name: catsdogs-api-lb
  namespace: catsdogs-mlops
spec:
  type: LoadBalancer
  selector:
    app: catsdogs-api
  ports:
    - name: http
      port: 80
      targetPort: 8000
